

#### DEVELOPMENT ####

demo:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?autoReconnect=true
    username: root
    password: mina89
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-wait: 10000
    test-on-borrow: true
    validation-query: select 1

paiq:
  attachment:
    public:
      path: C:\\test\\demo\\
#      path: /TEST/paiq/upload/